name: s_flutter_tree_view
version: 1.0.3
description: Package BK
homepage: https://bkholding.vn
publish_to: https://pub.s-erp.com.vn
repository: https://github.com/kieulan1912/flutter-tree-view.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
